# -*- coding: utf-8 -*-
"""Berfin_Python_Projesi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UL8o5Zfmzf9tQq9U1htboShAKZjVUDGB
"""

import os

# Dosya adını bir değişkende tutuyoruz ki her yerde kolayca kullanalım
dosya_adi = "gorevler.txt"

def dosya_oku():
    # Program ilk açıldığında çalışıp kayıtlı görevleri listeye çeken fonksiyon
    gorevler = []
    try:
        # utf-8 kullanıyoruz ki Türkçe karakterlerde (ş, ç, ğ vb.) sorun çıkmasın
        with open(dosya_adi, "r", encoding="utf-8") as dosya:
            for satir in dosya:
                # .strip() ile satır sonundaki görünmez enter (\n) karakterini siliyoruz
                gorevler.append(satir.strip())
        print("Görevler başarıyla yüklendi.")
    except FileNotFoundError:
        # Dosya yoksa hata vermek yerine yeni liste oluştuğunu bildiriyoruz
        print("Görev dosyası bulunamadı veya okunamadı. Yeni bir liste oluşturuldu.")
    return gorevler

def dosya_kaydet(gorevler):
    # Listede her değişiklik olduğunda (ekleme, silme, düzenleme) txt dosyasına yazan fonksiyon
    try:
        with open(dosya_adi, "w", encoding="utf-8") as dosya:
            for gorev in gorevler:
                dosya.write(gorev + "\n")
        print("Görevler başarıyla kaydedildi.")
    except Exception as e:
        print("Dosya kaydedilirken bir hata oluştu!")

def gorevleri_listele(gorevler):
    # Görevleri numaralandırarak ekrana basan fonksiyon
    print("\n--- GÖREV LİSTESİ ---")
    if len(gorevler) == 0:
        print("Henüz görev bulunmamaktadır.")
    else:
        # range ve len kullanarak numaraları 1'den başlatıp yazdırıyoruz
        for i in range(len(gorevler)):
            print(f"{i + 1}. {gorevler[i]}")
    print("-" * 25)

def gorev_ekle(gorevler):
    # Yeni görev ekleme fonksiyonu
    yeni_gorev = input("Yeni görev: ")
    # Sadece boşluğa basıp geçmesini engelliyoruz
    if yeni_gorev.strip() == "":
        print("Boş görev eklenemez!")
    else:
        gorevler.append(yeni_gorev)
        print(f"'{yeni_gorev}' görevi eklendi.")
        dosya_kaydet(gorevler) # Yönergedeki "her aşamada kaydetmeli" kuralı

def gorev_duzenle(gorevler):
    # Var olan bir görevi değiştirme fonksiyonu
    gorevleri_listele(gorevler)
    if len(gorevler) == 0:
        return # Liste boşsa düzenlenecek bir şey yoktur, menüye dön

    try:
        # Kullanıcıdan sayı bekliyoruz, harf girerse except bloğuna düşecek
        secim = input("Düzenlemek istediğiniz görevin numarası: ")
        numara = int(secim)

        # Girilen numara mantıklı bir aralıkta mı kontrolü
        if 1 <= numara <= len(gorevler):
            eski_gorev = gorevler[numara - 1]
            yeni_metin = input(f"Yeni görev metni ({eski_gorev}): ")

            if yeni_metin.strip() == "":
                print("Boş görev eklenemez!")
            else:
                # İndeksler 0'dan başladığı için kullanıcının girdiği sayıdan 1 çıkarıyoruz
                gorevler[numara - 1] = yeni_metin
                print("Görev başarıyla güncellendi.")
                dosya_kaydet(gorevler)
        else:
            print("Geçersiz görev numarası!")
    except ValueError:
        # Harf veya saçma bir karakter girildiğinde programın çökmesini engelliyoruz
        print("Lütfen bir sayı girin!")

def gorev_sil(gorevler):
    # Görev silme fonksiyonu (Düzenle fonksiyonuyla aynı hata kontrollerini içerir)
    gorevleri_listele(gorevler)
    if len(gorevler) == 0:
        return

    try:
        secim = input("Silmek istediğiniz görevin numarası: ")
        numara = int(secim)

        if 1 <= numara <= len(gorevler):
            # .pop() hem listeden çıkarır hem de çıkardığı değeri bize verir
            silinen_gorev = gorevler.pop(numara - 1)
            print(f"'{silinen_gorev}' görevi silindi.")
            dosya_kaydet(gorevler)
        else:
            print("Geçersiz görev numarası!")
    except ValueError:
        print("Lütfen bir sayı girin!")

def ana_program():
    # Sürekli dönen sonsuz döngü
    print("To-Do List Uygulamasına Hoş Geldiniz!")
    gorevler = dosya_oku()

    while True:
        print("\n--- TO-DO LIST UYGULAMASI ---")
        print("1. Görevleri Listele")
        print("2. Yeni Görev Ekle")
        print("3. Görev Düzenle")
        print("4. Görev Sil")
        print("5. Çıkış")

        secim = input("\nSeçiminiz (1-5): ")

        if secim == '1':
            gorevleri_listele(gorevler)
        elif secim == '2':
            gorev_ekle(gorevler)
        elif secim == '3':
            gorev_duzenle(gorevler)
        elif secim == '4':
            gorev_sil(gorevler)
        elif secim == '5':
            print("Programdan çıkılıyor...")
            break # Döngüyü kırar ve programı bitirir
        else:
            print("Geçersiz bir seçim yaptınız, lütfen 1 ile 5 arasında bir sayı girin.")

# Python'da programın başlangıç noktasını belirten standart yapı
if __name__ == "__main__":
    ana_program()